### ISSUE TITLE
Set environment variables in worker

### ISSUE THREAD

**Issue by ahallock** [iron-io/iron_worker_ruby_ng#132]
It would useful to add env variables to IronWorker in `.worker` (or another file in the worker upload). 

Additionally, you could set environment variables in the shell:

```
iron_worker env set <key> <value>
```

The available commands could be `list`, `get`, `set`, `delete`, and  `clear`.

The advantage with the CLI is that you could change env variables without having to re-upload the worker.

**Comment by brimatteng** [comment]
Has there been any update on this?

**Comment by niraltmark** [comment]
Same question, any update on the issue?

**Comment by alex-litvak** [comment]
@brimatteng, @niraltmark 
Just add this line to your .worker file
set_env 'VARIABLE_NAME', 'VARIABLE_VALUE'

**Comment by niraltmark** [comment]
Please see STRd6 commet, "for my situation I'd like to keep my .worker files and code in version control and keep my environment variables secret."

**Comment by thousandsofthem** [comment]
.worker content:

```
set_env 'token', ENV['token']
```

**Comment by niraltmark** [comment]
What you are saying is that the .worker file shouldn't be added to the source control?

**Comment by thousandsofthem** [comment]
It should, but .worker doesn't contain any secret info

**Comment by niraltmark** [comment]
It will if we will add AWS access key and secret key in order to upload content to S3.

**Comment by thousandsofthem** [comment]
How? .worker contain( proposed version) only references to environment variables, not values

**Comment by niraltmark** [comment]
It seems to me that we are speaking in different languages.

This is what you wrote "Just add this line to your .worker file  set_env 'VARIABLE_NAME', 'VARIABLE_VALUE'"
And now you wrote that the .worker shouldn't contains the values? So where and how can we set the values?

**Comment by thousandsofthem** [comment]
```
$ cat >> foo.worker
set_env 'token', ENV['token']
^D
$ export token=secret
$ iron_worker upload foo
```

**Comment by STRd6** [comment]
Thanks for the clarification, that will work for me.

**Comment by ruprict** [comment]
So, from what I am seeing, this doesn't work with the Docker workflow, since the .worker file is not needed. I tried adding it to the upload, but it didn't change anything. I'd love to be  wrong about this.

**Comment by thousandsofthem** [comment]
Yeah, `.worker` is not related to Docker workflow.
Still, you could pass environment variables via `config` feature.
use https://github.com/iron-io/iron_worker_ruby#ironworker-helper-functions to read it.
example:

```ruby
require 'iron_worker'

(IronWorker.config['vars'] || {}).each do |k,v|
   ENV[k] = v
end
```

config example (can be edited on "Code" page in the hud.iron.io):

```json
 {
  "vars":{
    "FOO":"bar",
    "KEY":"secret"
  }
}
```

**Comment by ruprict** [comment]
So, I decided to make a `config.json` file with my vars that looks like:

```
{
  "vars" : {
    "FOO" : "FOOVAL",
    "BAR" : "BARVAL" 
    } 
}

```
and then reference that file in the upload:

`iron worker upload -config-file="config.json" --stack ruby-2.1 worker.zip ruby worker.rb`

I have added `config.json` to `.gitignore`, obvs.

Works for me.  Thanks.
